# Generated by Django 3.1.8 on 2025-03-20 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('customization', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('order_date', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.mainuser')),
            ],
            options={
                'db_table': 'sp_order',
            },
        ),
    ]
