# Generated by Django 3.1.8 on 2025-03-20 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smartapp', '0003_auto_20250320_1950'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='audio_history/%Y/%m/%d/')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.device')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartapp.mainuser')),
            ],
            options={
                'db_table': 'sp_history',
            },
        ),
    ]
